spring.application.name=ems-backend

spring.datasource.url=jdbc:mysql://localhost:3306/db_ems
spring.datasource.username=ems
spring.datasource.password= ems@2026

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

